// POSTS
export const GET_POSTS = "GET_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
export const NEW_POST_FAILURE = "NEW_POST_FAILURE";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_CATEGORY_FILTER = "UPDATE_POST_CATEGORY_FILTER";
export const UPDATE_POST_DATE_ORDER = "UPDATE_POST_DATE_ORDER";

// CATEGORIES
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
// COMENTS
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const NEW_COMMENT = "NEW_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";

//ui
export const START_NETWORK = "START_NETWORK";
export const END_NETWORK = "END_NETWORK";

//api
export const API = "API";
