// POSTS
export const FETCHING_POSTS = "FETCHING_POSTS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const NEW_POST = "NEW_POST";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAILURE = "NEW_POST_FAILURE";
// CATEGORIES
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
// COMENTS
export const FETCH_COMMENTS = "FETCH_COMMENTS";
